spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mariadb://localhost:53307/on-boarding-java
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    database-platform: com.example.java_board._core.config.CustomMariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
